name: asmita_flutter
description: A new Flutter application.

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8  # Update to a null-safe version
  cloud_firestore: ^5.5.1
  firebase_database: ^11.2.0
  shared_preferences: ^2.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  file_picker: ^8.1.4
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2

  firebase_analytics: ^11.3.3 # Latest Firebase Analytics version
  firebase_messaging: ^15.1.3  # Latest Firebase Messaging version
  animated_text_kit: ^4.2.2  # Latest null-safe version
  path_provider: ^2.0.11
  http: ^1.2.2
  modal_progress_hud_nsn: ^0.5.1  # Use null-safe version of modal_progress_hud
  url_launcher: ^6.1.10  # Latest null-safe version
  intl: ^0.18.1  # Latest null-safe version
  flutter_pdfview: ^1.3.3 # Updated to null-safe version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/nunitosans_black.ttf